### ISSUE TITLE
major refactor of AllenSDK 2.4.0

### ISSUE THREAD

**Issue by dougollerenshaw** [AllenInstitute/visual_behavior_analysis#696]
AllenSDK rc2.4.0 has what appears to be some fairly substantial refactoring that breaks VBA.

So far, I've noted:
* BehaviorOphysLimsApi moved from allensdk.internal.api.behavior_ophys_api  to allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_lims_api

@wbwakeman or @njmei : do you know if there is (or will be) documentation of these changes in the release notes? That'd make fixes here more tractable. Also, any suggestions on how to implement changes to adapt to the new import syntax and still allow backward compatibility for older versions of the AllenSDK?

For reference, here's a screenshot of allensdk/internal/api in rc/2.3.2:
![image](https://user-images.githubusercontent.com/19944442/102562742-95ef0200-408c-11eb-913f-fcd301dea98f.png)

And the same in rc/2.4.0:

![image](https://user-images.githubusercontent.com/19944442/102562782-a7d0a500-408c-11eb-9697-40b1666e50f2.png)

@matchings, @alexpiet, @yavorska-iryna: This will require some attention relatively soon to allow VBA users to stay up to date on the AllenSDK

**Comment by njmei** [comment]
Hi @dougollerenshaw ,

Here is a summary of changes made in the refactor

- `allensdk.brain_observatory.behavior.internal` has been removed in favor of an organization that emphasizes "session" vs. "project" and "abstract base class" vs. "data featcher" related functionality
- `allensdk.internal.api.behavior_data_lims_api` and `allensdk.internal.api.behavior_lims_api` have been merged
- Many session APIs have been refactored into 'data processing' components (`allensdk.brain_observatory.behavior.session_apis.data_transforms`) and 'data IO' components (`allensdk.brain_observatory.behavior.session_apis.data_io`) to make code easier to follow and future maintenance easier to perform.

Changed imports:
- `from allensdk.brain_observatory.behavior.internal import BehaviorBase, BehaviorOphysBase` --> `from allensdk.brain_observatory.behavior.session_apis.abc import BehaviorBase, BehaviorOphysBase`
- `from allensdk.brain_observatory.behavior.internal.behavior_project_base import BehaviorProjectBase` --> `from allensdk.brain_observatory.behavior.project_apis.abcs.behavior_project_base import BehaviorProjectBase`
- `from allensdk.brain_observatory.behavior.behavior_project_lims_api import BehaviorProjectLimsApi` --> `from allensdk.brain_observatory.behavior.project_apis.data_io import  BehaviorProjectLimsApi`
- `from allensdk.brain_observatory.behavior.behavior_ophys_api.behavior_ophys_nwb_api import BehaviorOphysNwbApi` --> `from allensdk.brain_observatory.behavior.session_apis.data_io import BehaviorOphysNwbApi`
- `from allensdk.internal.api.behavior_ophys_api import  BehaviorOphysLimsApi` --> `allensdk.brain_observatory.behavior.session_apis.data_io import  BehaviorOphysLimsApi`
- `from allensdk.internal.api.ophys_lims_api import OphysLimsApi` --> `from allensdk.brain_observatory.behavior.session_apis.data_io.ophys_lims_api import OphysLimsApi`
- `from allensdk.internal.api.behavior_lims_api import BehaviorLimsApi` --> `from allensdk.brain_observatory.behavior.session_apis.data_io import BehaviorLimsApi`


I would be happy to go through with you if there are any other questions and/or comments

**Comment by dougollerenshaw** [comment]
Thanks @njmei! That's extremely helpful!

Is there a timeline for when 2.4.0 will become the default pip version? We may need to pin VBA at <=2.3.2 to avoid trouble until we're sure we've accounted for all of these import changes.

**Comment by njmei** [comment]
@dougollerenshaw 2.4.0 will probably be merged into master and released on pypi in the next week or two.

I've left a comment in the associated issue (https://github.com/AllenInstitute/AllenSDK/issues/1745) so that the dev who takes that on will contact you.

**Comment by dougollerenshaw** [comment]
Thanks @njmei!

**Comment by dougollerenshaw** [comment]
fixed in #701
