### ISSUE TITLE
Create lick annotation function

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_analysis#720]
Take code from the behavior model repo and add it to VBA
adds columns to the licks table:
- [ ] bout start
- [ ] bout end
- [ ] in bout
- [ ] ??

@matchings You can take a look at `get_metrics()` in this file
https://github.com/alexpiet/licking_behavior/blob/master/src/psy_metrics_tools.py

**Comment by dougollerenshaw** [comment]
@alexpiet what is 'in_bout' above?

**Comment by alexpiet** [comment]
Ignore that. I was confusing something from my function that annotates licking bouts onto the stimulus_presentations table
