### ISSUE TITLE
Annotate bouts on stimulus_presentations table

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_analysis#727]
Port this function https://github.com/alexpiet/licking_behavior/blob/master/src/psy_metrics_tools.py#L106

Adds columns to the stimulus_presentations table
- [ ] bout start
- [ ] bout_end

Although I can't think of a use case other than the behavior model, might be low priority

**Comment by dougollerenshaw** [comment]
Is that repo that you linked private? I see a 404 error when I click the link.

**Comment by alexpiet** [comment]
oh yeah I forgot that. I do dev work on my repo, and then I copy to an allen institute repo. I dont know what I have it set up that way.

Anyways you should be able to see this function: https://github.com/AllenInstitute/licking_behavior/blob/master/src/psy_metrics_tools.py#L106
