### ISSUE TITLE
add engagement state to trials df

### ISSUE THREAD

**Issue by farznaj** [AllenInstitute/visual_behavior_analysis#735]
i get trials df in the following way:
df = analysis.trials_response_df
but its engagement state (and mean_running speed) are all NaN. (it also doesnt have mean_pupil_area.)
however, if i get the stimulus df:
df = analysis.get_response_df(df_name='stimulus_response_df')
it contains valid values for all the above columns.
so it seems that trials df still does not contain the engagement state (and mean running , etc).
is that right?
can this be added easily? otherwise, how can i know which hits/misses were during which engagement (or running/pupil) state?

**Comment by dougollerenshaw** [comment]
Solved in PR #736
