### ISSUE TITLE
Cell metrics upgrades

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_analysis#792]
- [ ] It would be much faster if we saved out the metrics tables combined for all cells in the platform paper, rather than as individual experiments
- [ ] 'traces' metrics are missing
- [ ] `noise_level` metric
   - `noise_level = np.median(np.abs(np.diff(dff_trace)))/np.sqrt(ophys_frame_rate)`
   - https://gcamp6f.com/2021/10/04/large-scale-calcium-imaging-noise-levels/
   - I'm interested in this for the full-session-trace
- [ ] `mean_response` metric
   - For the full-session-trace.
   - This might just mean `np.mean(dff_trace)`
- [ ] `SNR` metric, just the ratio of the mean_response and noise level

**Comment by matchings** [comment]
question: do we want full trace metrics split by engaged vs. disengaged?

**Comment by alexpiet** [comment]
Those would probably be nice to have in addition to the full trace not split by engagement. I dont have any immediate use for them.

**Comment by alexpiet** [comment]
This was solved by https://github.com/AllenInstitute/visual_behavior_analysis/pull/797
