### ISSUE TITLE
Remove sessions that have been flagged for removal

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_analysis#794]
- [ ] Ophys_experiment_id = 856938751 has wild variability in image presentations time https://github.com/AllenInstitute/AllenSDK/issues/2252
- [ ] @matchings has other sessions/experiments that have been flagged, but not yet removed from the release data

**Comment by farznaj** [comment]
session_id	experiment_id	date	frame_dur
5	873720614	873963891	2019-05-22	0.178
6	873720614	873963889	2019-05-22	0.178
0	1048363441	1048483614	2020-09-04	0.11
1	1048363441	1048483611	2020-09-04	0.11
2	1048363441	1048483613	2020-09-04	0.11
3	1048363441	1048483616	2020-09-04	0.11
4	1048363441	1048483608	2020-09-04	0.11
5	1048363441	1048483604	2020-09-04	0.11
0	1049240847	1049610126	2020-09-09	0.11
1	1049240847	1049610123	2020-09-09	0.11
2	1049240847	1049610125	2020-09-09	0.11
3	1049240847	1049610129	2020-09-09	0.11
4	1049240847	1049610120	2020-09-09	0.11
5	1049240847	1049610116	2020-09-09	0.11
0	1050231786	1050485655	2020-09-14	0.11
1	1050231786	1050485652	2020-09-14	0.11
2	1050231786	1050485654	2020-09-14	0.11
3	1050231786	1050485657	2020-09-14	0.11
4	1050231786	1050485649	2020-09-14	0.11
5	1050231786	1050485645	2020-09-14	0.11
0	1050597678	1050762975	2020-09-15	0.11
1	1050597678	1050762972	2020-09-15	0.11
2	1050597678	1050762974	2020-09-15	0.11
3	1050597678	1050762977	2020-09-15	0.11
4	1050597678	1050762969	2020-09-15	0.11
5	1050597678	1050762966	2020-09-15	0.11
1	1051107431	1051249029	2020-09-17	0.11
2	1051107431	1051249031	2020-09-17	0.11
4	1051107431	1051249026	2020-09-17	0.11
1	1051319542	1051460016	2020-09-18	0.11
2	1051319542	1051460018	2020-09-18	0.11
1	1052096166	1052212179	2020-09-22	0.109
2	1052096166	1052212181	2020-09-22	0.109
5	1052096166	1052212170	2020-09-22	0.109
2	1052330675	1052412568	2020-09-23	0.109
5	1052330675	1052412559	2020-09-23	0.109
1	1052512524	1052637594	2020-09-24	0.109
2	1052512524	1052637596	2020-09-24	0.109
5	1052512524	1052637588	2020-09-24	0.109
1	1056065360	1056171531	2020-10-12	0.11
5	1056065360	1056171522	2020-10-12	0.11
1	1056238781	1057725804	2020-10-13	0.11
2	1056238781	1057725806	2020-10-13	0.11
5	1056238781	1057725798	2020-10-13	0.11

**Comment by farznaj** [comment]
The above mesoscope experiments have unusual frame duration.

**Comment by alexpiet** [comment]
To provide extra context, the sessions @farznaj lists are due to the set of sessions where mesoscope data was mistakenly collected at 9Hz. This issue documents the problem, but does not provide a solution. https://github.com/AllenInstitute/AllenSDK/issues/1762
